DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS project;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE project (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  category TEXT,
  languages TEXT,
  link TEXT,
  date_started DATE,
  video TEXT,
  photo TEXT,
  FOREIGN KEY (author_id) REFERENCES user (id)
);